# macOS only
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down
bind -T copy-mode-emacs C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-emacs C-WheelDownPane send-keys -X halfpage-down

# To copy, left click and drag to highlight text in yellow, 
# once you release left click yellow text will disappear and will automatically be available in clibboard
# # Use vim keybindings in copy mode
setw -g mode-keys vi
# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

#-------------------------------------------------------------------------------
# Terminal colors

# Set to use 256 colors
set -g default-terminal "screen-256color" 

#-------------------------------------------------------------------------------
# Theme

# Set status bar background color to colour232/black
set -g status-bg colour232

# Set windows backgrounded in the status bar to colour246/gray
set -g status-fg colour246

# Status bar refresh rate (seconds)
set -g status-interval 1

# Status bar character length
set -g status-left-length 30

# Sets current selected window to colour208/orange
set-window-option -g window-status-current-style fg=colour208

# Sets mode keys to use vim settings (for ? and / search in buffer scrolls)
set-window-option -g mode-keys vi

# On the left-side of status in green: print '{session_name} {user}@{hostname}'
set -g status-left '#[fg=green]#[default]'

# On the right of status in colour228/pastel_yellow : print time 'H:M m.d.y'
# set -g status-right '#[fg=colour228]Pane: #P | #[fg=colour228]%a %m/%d/%Y %I:%M:%S%P'
set -g status-right ''

# Set pane colors (Terminal must be using utf-8)
set -g pane-border-style bg=black
set -g pane-border-style fg=white
set -g pane-active-border-style bg=yellow
set -g pane-active-border-style fg=black

set -g pane-active-border-style fg=colour208,bg=default

# Note: To view all colors enabled
# for i in {0..255} ; do printf "\x1b[38;5;${i}mcolour${i}\n"; done
# set -g mode-style "fg=default,bg=default,reverse"
set-option -sg escape-time 10
